package pojos;
// Generated Sep 23, 2020 7:41:03 PM by Hibernate Tools 4.3.1



/**
 * PhonebookRecord generated by hbm2java
 */
public class PhonebookRecord  implements java.io.Serializable {

     private Integer id;
     private String firstName;
     private String lastName;
     private String number;

    public PhonebookRecord() {
    }

    public PhonebookRecord(String firstName, String lastName, String number) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.number = number;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    @Override
    public String toString() {
        return "PhonebookRecord{" + "id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", number=" + number + '}';
    }
}


